# Generated by Django 5.1.7 on 2025-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_post_views_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
