# Generated by Django 5.2 on 2025-04-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0008_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
