# Generated by Django 5.2 on 2025-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0013_alter_interviewpost_round_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewpost',
            name='round_type',
            field=models.CharField(choices=[('online_assessment', 'Online Assessment'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('system_design', 'System Design'), ('behavioral', 'Behavioral Interview')], max_length=30),
        ),
    ]
