# Generated by Django 5.1.7 on 2025-04-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpost',
            name='position',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
