# Generated by Django 5.1.7 on 2025-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_post_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpost',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
