# Generated by Django 5.1.7 on 2025-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0007_problem_difficulty_problemsolvelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='posts_app.userprofile'),
        ),
    ]
