# Generated by Django 5.2 on 2025-04-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0009_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsolvelog',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
