# Generated by Django 5.2 on 2025-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0010_problemsolvelog_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewpost',
            name='round_type',
            field=models.CharField(choices=[('application', 'Application'), ('online_assessment', 'Online Assessment'), ('technical_interview', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('system_design', 'System Design'), ('hr_interview', 'HR Interview'), ('team_match', 'Team Match')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('application', 'Application'), ('online_assessment', 'Online Assessment'), ('technical_interview', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('system_design', 'System Design'), ('hr_interview', 'HR Interview'), ('team_match', 'Team Match')], max_length=20),
        ),
    ]
