# Generated by Django 5.2 on 2025-04-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0011_alter_interviewpost_round_type_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewpost',
            name='round_type',
            field=models.CharField(choices=[('online_assessment', 'Online Assessment'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('system_design', 'System Design'), ('behavioral', 'Behavioral Interview')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('interview', 'Interview Experience'), ('general', 'General Discussion'), ('company_review', 'Company Review'), ('resume_submission', 'Resume Submission'), ('personal_record', 'Personal Record')], max_length=20),
        ),
    ]
